In [1]:
import datasets
from datasets import load_dataset

In [2]:
dataset = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_Electronics", split="full", trust_remote_code=True)

In [3]:
dataset[0]

{'main_category': 'All Electronics',
 'title': 'FS-1051 FATSHARK TELEPORTER V3 HEADSET',
 'average_rating': 3.5,
 'rating_number': 6,
 'features': [],
 'description': ['Teleporter V3 The “Teleporter V3” kit sets a new level of value in the FPV world with Fat Shark renowned performance and quality. The fun of FPV is experienced firsthand through the large screen FPV headset with integrated NexwaveRF receiver technology while simultaneously recording onboard HD footage with the included “PilotHD” camera. The “Teleporter V3” kit comes complete with everything you need to step into the cockpit of your FPV vehicle. We’ve included our powerful 250mW 5.8Ghz transmitter, 25 degree FOV headset (largest QVGA display available), the brand new “PilotHD” camera with live AV out and all the cables, antennas and connectors needed.'],
 'price': 'None',
 'images': {'hi_res': [None],
  'large': ['https://m.media-amazon.com/images/I/41qrX56lsYL._AC_.jpg'],
  'thumb': ['https://m.media-amazon.com/images/I/41qrX56lsYL._AC_US40_.jpg'],
  'variant': ['MAIN']},
 'videos': {'title': [], 'url': [], 'user_id': []},
 'store': 'Fat Shark',
 'categories': ['Electronics', 'Television & Video', 'Video Glasses'],
 'details': '{"Date First Available": "August 2, 2014", "Manufacturer": "Fatshark"}',
 'parent_asin': 'B00MCW7G9M',
 'bought_together': None,
 'subtitle': None,
 'author': None}

In [4]:
len(dataset)

1610012

In [5]:
from tqdm import tqdm
meta_id, meta_item_id = [], []
for idx, data in enumerate(tqdm(dataset)):
    meta_id.append(idx)
    meta_item_id.append(data["parent_asin"])

100%|██████████| 1610012/1610012 [04:15<00:00, 6295.02it/s]

In [6]:
import pandas as pd
meta_df = pd.DataFrame({
    "meta_id": meta_id,
    "meta_item_id": meta_item_id
})
meta_df

         meta_id meta_item_id
0              0   B00MCW7G9M
1              1   B00YT6XQSE
2              2   B07SM135LS
3              3   B089CNGZCW
4              4   B004E2Z88O
...          ...          ...
1610007  1610007   B003NUIU9M
1610008  1610008   B0BHVY33TL
1610009  1610009   B09SQGRFFH
1610010  1610010   B091JWCSG5
1610011  1610011   B08K7KC4GR

[1610012 rows x 2 columns]

In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv("../../data/raw/Electronics.csv")
df

                               user_id parent_asin  rating      timestamp
0         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B0047T79VS     3.0  1344406083000
1         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01HHURN3W     3.0  1408995743000
2         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B00L0YLRUW     1.0  1439226089000
3         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B017T99JPG     5.0  1456772365000
4         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01LW71IBJ     5.0  1456772571000
...                                ...         ...     ...            ...
15473531  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B0798VJN3Z     5.0  1520311945584
15473532  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B09DGTFFG2     5.0  1520312077441
15473533  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B01M9FJHVT     5.0  1521548986182
15473534  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B075NJLMR8     5.0  1521549405374
15473535  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B00L9GIJMU     4.0  1521549555159

[15473536 rows x 4 columns]

In [8]:
unique_item_id = df["parent_asin"].unique()
len(unique_item_id)

368228

In [9]:
unique_item_df = pd.DataFrame({
    "meta_item_id": unique_item_id
})
unique_item_df

       meta_item_id
0        B0047T79VS
1        B01HHURN3W
2        B00L0YLRUW
3        B017T99JPG
4        B01LW71IBJ
...             ...
368223   B0BZTVZ4XV
368224   B0C5RJYKN7
368225   B0CGRQP1K1
368226   B0C7Z8R294
368227   B0C746TY77

[368228 rows x 1 columns]

In [10]:
item_df = pd.merge(meta_df, unique_item_df, how="inner", on="meta_item_id")
item_df

        meta_id meta_item_id
0             0   B00MCW7G9M
1             2   B07SM135LS
2             3   B089CNGZCW
3             4   B004E2Z88O
4             5   B00TX536EK
...         ...          ...
368223  1599176   B0BHVHQ6NR
368224  1599316   B0BHSP7BGD
368225  1605611   B0CGHG8Y7H
368226  1608306   B0C24HF7P4
368227  1609816   B0BZ8K2LJX

[368228 rows x 2 columns]

In [11]:
item_df.to_pickle("../../data/interim/meta.pkl")

In [12]:
meta_json = [dataset[idx] for idx in item_df["meta_id"].tolist()]
import json
json.dump(meta_json, open("../../data/interim/meta.json", "w"))

In [13]:
df = pd.DataFrame({
    "title": [item["title"] for item in meta_json], 
    "categories":[item["categories"] for item in meta_json], 
    "main_category":[item["main_category"] for item in meta_json], 
    "average_rating": [item["average_rating"] for item in meta_json], 
    "description": [item["description"] for item in meta_json],  
    "images": [item["images"] for item in meta_json], 
    "price":[item["price"] for item in meta_json], 
    "parent_asin": [item["parent_asin"] for item in meta_json], 
    "rating_number": [item["rating_number"] for item in meta_json], 
})
df

,title,categories,main_category,average_rating,description,images,price,parent_asin,rating_number
0,FS-1051 FATSHARK TELEPORTER V3 HEADSET,"[Electronics, Television & Video, Video Glasses]",All Electronics,3.5,[Teleporter V3 The “Teleporter V3” kit sets a ...,"{'hi_res': [None], 'large': ['https://m.media-...",None,B00MCW7G9M,6
1,Digi-Tatoo Decal Skin Compatible With MacBook ...,"[Electronics, Computers & Accessories, Laptop ...",Computers,4.5,[],{'hi_res': ['https://m.media-amazon.com/images...,19.99,B07SM135LS,246
2,NotoCity Compatible with Vivoactive 4 band 22m...,"[Electronics, Wearable Technology, Clips, Arm ...",AMAZON FASHION,4.5,[],{'hi_res': ['https://m.media-amazon.com/images...,9.99,B089CNGZCW,233
3,Motorola Droid X Essentials Combo Pack,"[Electronics, Computers & Accessories, Compute...",Cell Phones & Accessories,3.8,[all Genuine High Quality Motorola Made Access...,"{'hi_res': [None, None, None, None, None], 'la...",14.99,B004E2Z88O,64
4,Raymarine Wi-Fish DownVision Blackbox Sonar wi...,"[Electronics, Car & Vehicle Electronics, Marin...",Sports & Outdoors,3.5,[Transform your smartphone into a powerful CHI...,{'hi_res': ['https://m.media-amazon.com/images...,None,B00TX536EK,25
...,...,...,...,...,...,...,...,...,...
368223,HBT Waterproof Airtag Holder/AirTag Keychain C...,"[Electronics, Headphones, Earbuds & Accessorie...",None,4.4,[],{'hi_res': ['https://m.media-amazon.com/images...,25.99,B0BHVHQ6NR,66
368224,Monster N-Lite Clear Talk Wireless Earbuds Blu...,"[Electronics, Headphones, Earbuds & Accessorie...",None,4.2,[],{'hi_res': ['https://m.media-amazon.com/images...,39.99,B0BHSP7BGD,125
368225,[Apple MFi Certified] Coiled Lightning Cable f...,"[Electronics, Computers & Accessories, Compute...",Industrial & Scientific,4.2,"[Coiled Apple Carplay Cable,3ft Coiled Lightni...",{'hi_res': ['https://m.media-amazon.com/images...,8.99,B0CGHG8Y7H,148
368226,"trueCABLE Cat6 Plenum (CMP), 1000ft, Green, 23...","[Electronics, Computers & Accessories, Compute...",Industrial & Scientific,4.5,[],{'hi_res': ['https://m.media-amazon.com/images...,318.99,B0C24HF7P4,131
368227,Lekaby Wireless Earbuds Bluetooth 5.3 Headphon...,"[Electronics, Headphones, Earbuds & Accessorie...",All Electronics,5.0,[],{'hi_res': ['https://m.media-amazon.com/images...,None,B0BZ8K2LJX,162

In [14]:
df.to_pickle("../../data/interim/item_meta.pkl")