In [1]:
import pandas as pd
import numpy as np
NUM_USER, NUM_ITEM = 2_000, 300_000
df = pd.read_csv("../../data/raw/Electronics.csv")
df

                               user_id parent_asin  rating      timestamp
0         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B0047T79VS     3.0  1344406083000
1         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01HHURN3W     3.0  1408995743000
2         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B00L0YLRUW     1.0  1439226089000
3         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B017T99JPG     5.0  1456772365000
4         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01LW71IBJ     5.0  1456772571000
...                                ...         ...     ...            ...
15473531  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B0798VJN3Z     5.0  1520311945584
15473532  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B09DGTFFG2     5.0  1520312077441
15473533  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B01M9FJHVT     5.0  1521548986182
15473534  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B075NJLMR8     5.0  1521549405374
15473535  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B00L9GIJMU     4.0  1521549555159

[15473536 rows x 4 columns]

In [2]:
top_user_df = df.groupby("user_id").agg({
    "parent_asin": lambda x: x.tolist(),
    "rating": lambda x: x.tolist(),
    "timestamp": lambda x: x.tolist(),
}).reset_index(drop=False)
top_user_df["item_len"] = top_user_df["rating"].apply(lambda x: len(x))
top_user_df

,user_id,parent_asin,rating,timestamp,item_len
0,AE22236AFRRSMQIKGG7TPTB75QEA,"[B0007MGG2M, B000ELSZBQ, B000XT3L7W, B00297IPU...","[5.0, 2.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, ...","[1143213544000, 1174661490000, 1234625406000, ...",21
1,AE2227QSJSF6HV3XTTIGQAPA6WHQ,"[B07RLHLXLC, B08DLSLCF3, B0BFLMSQQ3, B0BXPPZ3M...","[4.0, 4.0, 5.0, 5.0, 4.0]","[1598308362367, 1620244930293, 1640623487248, ...",5
2,AE222H3FGXWLHRFUMGMS2RR57NDQ,"[B0049XEE88, B004GI6PCY, B006K0X1HI, B002I9WCW...","[4.0, 4.0, 4.0, 4.0, 5.0, 4.0, 4.0, 3.0, 4.0, ...","[1381408252000, 1383657058000, 1389108590000, ...",16
3,AE222HFVDJ4TJ4V2LDRIAMQM2RPA,"[B005UASI0E, B00BLCLURI, B00E1TOO8U, B007R6F7P...","[4.0, 4.0, 5.0, 5.0, 4.0, 5.0]","[1373639560000, 1373639839000, 1424629913000, ...",6
4,AE222KSFP7UXSULU6I34OU2A2DUQ,"[B07KM1CY1P, B01K4A6JHS, B00RJC9RU6, B01AT23UG...","[5.0, 5.0, 5.0, 5.0, 5.0]","[1404200740000, 1440961767000, 1485416436000, ...",5
...,...,...,...,...,...
1641021,AHZZZWVHLYTQU55PD4FJULUEKTXA,"[B00EL0J81M, B00C981DDY, B00J02VUJ4, B00E3A4OI...","[5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 2.0, ...","[1404755540000, 1410014749000, 1421554792000, ...",16
1641022,AHZZZX5LNNKLAZCTZNB6F445ZIIQ,"[B0851JXH5T, B083ZJYDRV, B08N9DPW69, B0C5PHZ4Q...","[4.0, 5.0, 5.0, 5.0, 5.0]","[1603128927844, 1615491737353, 1615491775723, ...",5
1641023,AHZZZY2XVWEUJUTYPGGL4WXH6CSA,"[B002MRMCKU, B001F7AJKI, B001AW8W7A, B00U43F99...","[2.0, 5.0, 5.0, 2.0, 5.0, 5.0, 5.0, 5.0, 1.0, ...","[1307549781000, 1464030507000, 1464030553000, ...",19
1641024,AHZZZYCUOTRYW4ZQFIFAEZGBOY4A,"[B00EEOSZK0, B00M58CMYC, B00JJGFRIQ, B00E8HIN7...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.0]","[1416942517000, 1416942571000, 1416942597000, ...",7
1641025,AHZZZZPE45DYV2WZ2MYXZRHWSEKA,"[B004J22FM6, B00IYA2ZJW, B0B4DFWFS6, B00UGA6QI...","[5.0, 4.0, 5.0, 5.0, 5.0, 3.0, 5.0, 1.0, 5.0]","[1357962215000, 1457727617000, 1481307350000, ...",9

In [3]:
item_lens = top_user_df["item_len"].to_numpy()

top_user_df = top_user_df.iloc[np.argsort(item_lens)[::-1][:NUM_USER]].reset_index(drop=True)
top_user_df

,user_id,parent_asin,rating,timestamp,item_len
0,AEIIRIHLIYKQGI7ZOCIJTRDF5NPQ,"[B0036DDT42, B003DTLV8K, B002OHDGSA, B07Q8C334...","[1.0, 2.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 4.0, ...","[1268942347000, 1305832844000, 1305833399000, ...",938
1,AHMNA5UK3V66O2V3DZSBJA4FYMOA,"[B00006LIOM, B000AA2IC8, B0002OKCX4, B0009I96L...","[5.0, 4.0, 3.0, 5.0, 2.0, 4.0, 5.0, 5.0, 5.0, ...","[1111978505000, 1127359441000, 1141513984000, ...",852
2,AHSV5AUFONH7QMMUPF7M6FUJRJ6Q_1,"[B07VB65SDK, B07HBRTQD1, B015GEUKC2, B09G6SKX2...","[4.0, 5.0, 4.0, 5.0, 5.0, 3.0, 5.0, 5.0, 3.0, ...","[1584500236017, 1584500370087, 1584500428254, ...",750
3,AECTQQX663PTF5UQ2RA5TUL3BXVQ,"[B00004SB92, B0000AINE1, B000231GU8, B0001MHYK...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 3.0, ...","[1104181609000, 1104181932000, 1104182321000, ...",692
4,AFTZWAK3ZHAPCNSOT5GCKQDECBTQ,"[B07K1R6CQY, B08MTJXHPP, B01F9RGWF0, B08Q3QPZ5...","[4.0, 4.0, 1.0, 3.0, 2.0, 2.0, 1.0, 2.0, 2.0, ...","[1551214741572, 1587758103257, 1590865969450, ...",629
...,...,...,...,...,...
1995,AGWJ3WOKO6JPVGAPDSYZJCAOAD2Q,"[B07S764D9V, B007I55JVK, B00IEESN0S, B00M48154...","[5.0, 5.0, 5.0, 5.0, 5.0, 1.0, 5.0, 5.0, 5.0, ...","[1423792748000, 1423793528000, 1423793788000, ...",92
1996,AEG5GD65LQUYTLPE24UM53WHI3RQ,"[B003VANOFY, B017DYKCNA, B00KPZM9AY, B007XDA42...","[3.0, 3.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, ...","[1455870180000, 1455870380000, 1455870717000, ...",92
1997,AHTYHQ2ZFOMSSOCPEBGD7TDCIWFA,"[B002882NB6, B003DV71DW, B00194OJU8, B000Q8UAW...","[4.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[1285975005000, 1287524227000, 1287528267000, ...",92
1998,AEFGKWZP7O63NB7GQSXWBUHCVNPQ,"[B0001G6U3Y, B003VYB1KK, B0079T9HL8, B00843ERM...","[5.0, 4.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 1.0, ...","[1195585248000, 1284518729000, 1378765856000, ...",92
1999,AH7RYXFDGYQYHKLT4XHCVJ2XJ25A,"[B07P1FN7KQ, B00318CGFK, B000051299, B07RWDZ3H...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 2.0, 5.0, ...","[1282713645000, 1283353479000, 1283354170000, ...",92

In [4]:
top_item_df = df.groupby("parent_asin").agg({
    "user_id": lambda x: x.tolist(),
    "rating": lambda x: x.tolist(),
    "timestamp": lambda x: x.tolist(),
}).reset_index(drop=False)
top_item_df["user_len"] = top_item_df["rating"].apply(lambda x: len(x))
top_item_df

,parent_asin,user_id,rating,timestamp,user_len
0,0062970704,"[AFUSWNVA72MMWHGYWJ652SYX2JJQ, AEX572KCHWTIW45...","[5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[1574625300520, 1621464729391, 1578846094359, ...",256
1,0071341196,"[AGFP4L46THLV4ZT2OKLNYP7FZ3LQ, AH263ZZPY6WT53H...","[5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, ...","[1578173031817, 1292138499000, 1519408286370, ...",12
2,0140194614,"[AHCEZWPAA7PN47RVSNM22RVQJWCA, AHN3GXGA6X7QVQ5...","[5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, ...","[1331508697000, 1378503025000, 1490626534000, ...",13
3,0224073087,"[AG2RASOW27UAC37NQ53BAEXPC7IQ, AGC5XIO3A6IOMST...","[1.0, 4.0, 5.0, 3.0, 5.0]","[1433908964000, 1473204292000, 1441208274000, ...",5
4,0321528859,"[AFZFUIU3BWQ6UYQCUPZ5D6GVRS7A, AHMGBZBHCAYCUPW...","[5.0, 5.0, 4.0, 3.0, 2.0, 5.0, 4.0, 3.0]","[1239464798000, 1424117477000, 1471471481000, ...",8
...,...,...,...,...,...
368223,B0CJ66R5H2,"[AEHWGQSOFNOTX2QPHSIAFKC7CTNA, AERYN7BWF5Y5FRK...","[5.0, 1.0, 5.0, 4.0, 4.0]","[1683293649329, 1684290202466, 1683545442303, ...",5
368224,B0CJMJ22ZQ,"[AFHNITCJVVIK4RNIDDO3VWXLAPFA, AF77IMLF3ZL7MPI...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]","[1682827261129, 1683098173403, 1683554219914, ...",7
368225,B0CK2GYBK7,"[AGBXNANDMFG2B5Z35QPFDAZ6K7MQ, AH2CZB5YW5AWBED...","[5.0, 5.0, 5.0, 5.0, 5.0]","[1684615439308, 1685115928359, 1686111181551, ...",5
368226,B0CK88843T,"[AGMVGVFYNKE4EPHBBAUWBGZBIWZQ, AHNQKGSHAVU4AN4...","[4.0, 5.0, 5.0, 5.0, 5.0, 5.0]","[1686539061409, 1687221012551, 1685797400644, ...",6
368227,b014k9dj72,"[AHYMYFCLBNSFCPXW72DEMHJJFOIA, AHVSFC4Y4MIUO7N...","[3.0, 5.0, 5.0, 3.0, 5.0]","[1472787595000, 1486597568000, 1494465784000, ...",5

In [5]:
user_lens = top_item_df["user_len"].to_numpy()

top_item_df = top_item_df.iloc[np.argsort(user_lens)[::-1][:NUM_ITEM]].reset_index(drop=True)
top_item_df

,parent_asin,user_id,rating,timestamp,user_len
0,B075X8471B,"[AHGAOIZVODNHYMNCBV4DECZH42UQ, AEDHXXX2F66EMWO...","[5.0, 4.0, 5.0, 5.0, 2.0, 5.0, 5.0, 5.0, 5.0, ...","[1532476996921, 1482384682000, 1537322362789, ...",44948
1,B01K8B8YA8,"[AHGAOIZVODNHYMNCBV4DECZH42UQ, AFZUK3MTBIBEDQO...","[5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, ...","[1513557475457, 1507749572526, 1538837322940, ...",39313
2,B07GZFM1ZM,"[AFZUK3MTBIBEDQOPAK3OATUOUKLA, AGJY4LG74YJEJBV...","[5.0, 5.0, 5.0, 1.0, 5.0, 5.0, 5.0, 1.0, 5.0, ...","[1586731581372, 1577755436567, 1545354325131, ...",36533
3,B010BWYDYA,"[AG57CQ6P4QWYMWUV6MTAOETUKHTA, AGA3PQKDGXZQB7D...","[5.0, 4.0, 2.0, 4.0, 5.0, 5.0, 4.0, 2.0, 5.0, ...","[1450507957000, 1469711844000, 1473698337000, ...",26228
4,B07S764D9V,"[AFA26DYXVLJYTYZ3KET77GE27N2A, AGUQFBJGLRCTSY4...","[5.0, 4.0, 4.0, 5.0, 4.0, 2.0, 2.0, 1.0, 5.0, ...","[1562372039826, 1456417953000, 1611676147082, ...",21534
...,...,...,...,...,...
299995,B073TSDVJH,"[AGPRHVE5JXPX2YJVTE47C7L2K2QA, AEH7MBYDM2WNJPY...","[3.0, 5.0, 2.0, 1.0, 5.0, 5.0]","[1605656625668, 1583425264879, 1535923696004, ...",6
299996,B01GKLJ5YE,"[AHA52NPNJ2RQRMRV42ZNI2KP4AYA, AGIPHBKILJ2RGTE...","[5.0, 4.0, 5.0, 2.0, 5.0, 3.0]","[1510327203275, 1529677854542, 1472672603000, ...",6
299997,B07DW391KT,"[AEC3VEUL4DMWHXBL55LPO7VSX37A, AF3JOOBW5RS34LN...","[5.0, 4.0, 5.0, 1.0, 5.0, 5.0]","[1573783416501, 1565179234243, 1577499354663, ...",6
299998,B0BG1BP7FK,"[AEQJ56BY6JCQD2YH7C73J2FOPQ2Q, AEWHWX2ALEUISH7...","[5.0, 4.0, 5.0, 4.0, 4.0, 5.0]","[1668696826119, 1666629772330, 1666993518967, ...",6
299999,B07DW4RG3H,"[AH7WE3OPVFXYMRIT3VXUIUUIVPDQ, AER64HEE2C5DUDD...","[5.0, 5.0, 1.0, 3.0, 4.0, 5.0]","[1566085412619, 1589981484003, 1600369189769, ...",6

In [6]:
top_user_df = top_user_df.explode(["parent_asin", "rating", "timestamp"])

In [7]:
top_item_df = top_item_df.explode(["user_id", "rating", "timestamp"])

In [8]:
ddf = pd.merge(top_item_df, top_user_df, on=["user_id", "parent_asin"], how="inner")[["parent_asin", "user_id", "timestamp_x", "rating_x"]]
ddf = ddf.rename(columns={
    "rating_x": "rating", 
    "timestamp_x": "timestamp"
})
ddf

       parent_asin                       user_id      timestamp rating
0       B075X8471B  AHPOHKN4PU4W3V5PGFL7AGTAD2AA  1519588050500    4.0
1       B075X8471B  AE2ODZ4VYQ5FNNCONSHSNZM7PHSQ  1538170949468    5.0
2       B075X8471B  AG63W2BMC4HRP76AMS36AYY64AHA  1522002054268    5.0
3       B075X8471B  AHEWMIIM4SK7YNFZ3IADPCX4ARVQ  1515634019259    5.0
4       B075X8471B  AHQVC5ZUMGV5CLH4GUI2TZRUSLUA  1520375158280    3.0
...            ...                           ...            ...    ...
263881  B00YH2I054  AF23U6N5FDX3VN7QFZIHZRBNZOEQ  1463411202000    1.0
263882  B07DW7M2V9  AFLW4QVB6RU6ATQT43KZCDBVZYEA  1546818131702    4.0
263883  B0BG1Q3787  AFVV3PU2DXKRDEJ4DO22IMOFX2UQ  1677144915398    5.0
263884  B0BG1Q3787  AEUMMLWQFAJOZ3W3QEXVQQLHPE7A  1681568239616    5.0
263885  B0BG1T7D5Y  AF7P6F3PRRGUNG6IVHDGJ7K7PCGQ  1669775462443    4.0

[263886 rows x 4 columns]

In [9]:
ddf = ddf.groupby("parent_asin").agg({
    "user_id": lambda x: x.tolist(),
    "rating": lambda x: x.tolist(),
    "timestamp": lambda x: x.tolist(),
}).reset_index(drop=False)

ddf["item_id"] = [i for i in range(len(ddf))]
ddf = ddf.explode(["user_id", "rating", "timestamp"])
ddf

      parent_asin                       user_id rating      timestamp  item_id
0      0062970704  AFUSWNVA72MMWHGYWJ652SYX2JJQ    5.0  1574625300520        0
0      0062970704  AFKKKGCSWQR5TKJPAFPLHF7VT26Q    5.0  1578518997397        0
0      0062970704  AF467J5VV3PDUURMEZOMXEHWFVMA    5.0  1577396717283        0
1      0511189877  AGFPQCUEVTD3AFRO4O3ZV3BQQE6Q    5.0  1413844836000        1
1      0511189877  AGHAGIX4CAVFNGVUVJSYKXY47D7A    5.0  1472156129000        1
...           ...                           ...    ...            ...      ...
97715  B0CHR7WTKX  AHALYOX63S6CACZTHN7R24RVEX2A    5.0  1381060952000    97715
97715  B0CHR7WTKX  AFERKAUNTMTHHES5KZPJN3FL6BOQ    5.0  1357640292000    97715
97715  B0CHR7WTKX  AHTYHQ2ZFOMSSOCPEBGD7TDCIWFA    5.0  1328406619000    97715
97716  B0CHR8FLG4  AFYKLKXDGO2JRHHAVDCPFGBUBSCA    5.0  1435417223000    97716
97717  B0CHVM9VP2  AFLABIBLTVBHSWCDT6CVWJ2BPTFQ    5.0  1661884597294    97717

[263886 rows x 5 columns]

In [10]:
ddf = ddf.groupby("user_id").agg({
    "item_id": lambda x: x.tolist(),
    "parent_asin": lambda x: x.tolist(),
    "rating": lambda x: x.tolist(),
    "timestamp": lambda x: x.tolist(),
}).reset_index(drop=False)

ddf["user_id"] = [i for i in range(len(ddf))]
ddf = ddf.explode(["item_id", "parent_asin", "rating", "timestamp"])
ddf

      user_id item_id parent_asin rating      timestamp
0           0     556  B00006HVLW    2.0  1487119257000
0           0     843  B00009R6NZ    2.0  1421898485000
0           0    1039  B0000BZL05    5.0  1479153808000
0           0    3865  B000SAKX90    5.0  1428545901000
0           0    4646  B00139XOCI    3.0  1400166889000
...       ...     ...         ...    ...            ...
1999     1999   94625  B0BZZ6LR4F    5.0  1673978794550
1999     1999   95168  B0C2VL26VV    4.0  1611838236946
1999     1999   96036  B0C5C9S5BF    4.0  1542761097586
1999     1999   96165  B0C5MTHGZG    5.0  1644327808915
1999     1999   96765  B0C7BLFNR5    4.0  1668806489965

[263886 rows x 5 columns]

In [11]:
len(ddf["item_id"].unique()), len(ddf["user_id"].unique())

(97718, 2000)

In [15]:
ddf.to_pickle("../../data/interim/rating.pkl")