In [1]:
import pandas as pd
import numpy as np
NUM_USER, NUM_ITEM = 5_000, 30_000
df = pd.read_csv("../../data/raw/Electronics.csv")
df

                               user_id parent_asin  rating      timestamp
0         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B0047T79VS     3.0  1344406083000
1         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01HHURN3W     3.0  1408995743000
2         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B00L0YLRUW     1.0  1439226089000
3         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B017T99JPG     5.0  1456772365000
4         AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01LW71IBJ     5.0  1456772571000
...                                ...         ...     ...            ...
15473531  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B0798VJN3Z     5.0  1520311945584
15473532  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B09DGTFFG2     5.0  1520312077441
15473533  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B01M9FJHVT     5.0  1521548986182
15473534  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B075NJLMR8     5.0  1521549405374
15473535  AFEOYBNEUFEXOKEUW2RQTD4TOFMQ  B00L9GIJMU     4.0  1521549555159

[15473536 rows x 4 columns]

In [2]:
top_user_df = df.groupby("user_id").agg({
    "parent_asin": lambda x: x.tolist(),
    "rating": lambda x: x.tolist(),
    "timestamp": lambda x: x.tolist(),
}).reset_index(drop=False)
top_user_df["item_len"] = top_user_df["rating"].apply(lambda x: len(x))
top_user_df

,user_id,parent_asin,rating,timestamp,item_len
0,AE22236AFRRSMQIKGG7TPTB75QEA,"[B0007MGG2M, B000ELSZBQ, B000XT3L7W, B00297IPU...","[5.0, 2.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, ...","[1143213544000, 1174661490000, 1234625406000, ...",21
1,AE2227QSJSF6HV3XTTIGQAPA6WHQ,"[B07RLHLXLC, B08DLSLCF3, B0BFLMSQQ3, B0BXPPZ3M...","[4.0, 4.0, 5.0, 5.0, 4.0]","[1598308362367, 1620244930293, 1640623487248, ...",5
2,AE222H3FGXWLHRFUMGMS2RR57NDQ,"[B0049XEE88, B004GI6PCY, B006K0X1HI, B002I9WCW...","[4.0, 4.0, 4.0, 4.0, 5.0, 4.0, 4.0, 3.0, 4.0, ...","[1381408252000, 1383657058000, 1389108590000, ...",16
3,AE222HFVDJ4TJ4V2LDRIAMQM2RPA,"[B005UASI0E, B00BLCLURI, B00E1TOO8U, B007R6F7P...","[4.0, 4.0, 5.0, 5.0, 4.0, 5.0]","[1373639560000, 1373639839000, 1424629913000, ...",6
4,AE222KSFP7UXSULU6I34OU2A2DUQ,"[B07KM1CY1P, B01K4A6JHS, B00RJC9RU6, B01AT23UG...","[5.0, 5.0, 5.0, 5.0, 5.0]","[1404200740000, 1440961767000, 1485416436000, ...",5
...,...,...,...,...,...
1641021,AHZZZWVHLYTQU55PD4FJULUEKTXA,"[B00EL0J81M, B00C981DDY, B00J02VUJ4, B00E3A4OI...","[5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 5.0, 2.0, ...","[1404755540000, 1410014749000, 1421554792000, ...",16
1641022,AHZZZX5LNNKLAZCTZNB6F445ZIIQ,"[B0851JXH5T, B083ZJYDRV, B08N9DPW69, B0C5PHZ4Q...","[4.0, 5.0, 5.0, 5.0, 5.0]","[1603128927844, 1615491737353, 1615491775723, ...",5
1641023,AHZZZY2XVWEUJUTYPGGL4WXH6CSA,"[B002MRMCKU, B001F7AJKI, B001AW8W7A, B00U43F99...","[2.0, 5.0, 5.0, 2.0, 5.0, 5.0, 5.0, 5.0, 1.0, ...","[1307549781000, 1464030507000, 1464030553000, ...",19
1641024,AHZZZYCUOTRYW4ZQFIFAEZGBOY4A,"[B00EEOSZK0, B00M58CMYC, B00JJGFRIQ, B00E8HIN7...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 1.0]","[1416942517000, 1416942571000, 1416942597000, ...",7
1641025,AHZZZZPE45DYV2WZ2MYXZRHWSEKA,"[B004J22FM6, B00IYA2ZJW, B0B4DFWFS6, B00UGA6QI...","[5.0, 4.0, 5.0, 5.0, 5.0, 3.0, 5.0, 1.0, 5.0]","[1357962215000, 1457727617000, 1481307350000, ...",9

In [3]:
item_lens = top_user_df["item_len"].to_numpy()

top_user_df = top_user_df.iloc[np.argsort(item_lens)[::-1][:NUM_USER]].reset_index(drop=True)
top_user_df

,user_id,parent_asin,rating,timestamp,item_len
0,AEIIRIHLIYKQGI7ZOCIJTRDF5NPQ,"[B0036DDT42, B003DTLV8K, B002OHDGSA, B07Q8C334...","[1.0, 2.0, 5.0, 5.0, 4.0, 4.0, 4.0, 5.0, 4.0, ...","[1268942347000, 1305832844000, 1305833399000, ...",938
1,AHMNA5UK3V66O2V3DZSBJA4FYMOA,"[B00006LIOM, B000AA2IC8, B0002OKCX4, B0009I96L...","[5.0, 4.0, 3.0, 5.0, 2.0, 4.0, 5.0, 5.0, 5.0, ...","[1111978505000, 1127359441000, 1141513984000, ...",852
2,AHSV5AUFONH7QMMUPF7M6FUJRJ6Q_1,"[B07VB65SDK, B07HBRTQD1, B015GEUKC2, B09G6SKX2...","[4.0, 5.0, 4.0, 5.0, 5.0, 3.0, 5.0, 5.0, 3.0, ...","[1584500236017, 1584500370087, 1584500428254, ...",750
3,AECTQQX663PTF5UQ2RA5TUL3BXVQ,"[B00004SB92, B0000AINE1, B000231GU8, B0001MHYK...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 3.0, ...","[1104181609000, 1104181932000, 1104182321000, ...",692
4,AFTZWAK3ZHAPCNSOT5GCKQDECBTQ,"[B07K1R6CQY, B08MTJXHPP, B01F9RGWF0, B08Q3QPZ5...","[4.0, 4.0, 1.0, 3.0, 2.0, 2.0, 1.0, 2.0, 2.0, ...","[1551214741572, 1587758103257, 1590865969450, ...",629
...,...,...,...,...,...
4995,AF5FIGOXCMO3ATZZOSKB5ASIPNZQ,"[B001QENO7A, B08M3TZBQ9, B00HGE3CWG, B0039BPG1...","[5.0, 2.0, 3.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[1242670497000, 1420854952000, 1431212249000, ...",67
4996,AEXKCKYUAKBCPT6TBV7JX3POSOZQ,"[B002G1YPH0, B00653OOPS, B007USQ3YW, B00385XUF...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[1338823688000, 1340254070000, 1340556569000, ...",67
4997,AFQYIU6CMK6QCGGBTWGPYAS23LTA,"[B001G4LODG, B0000AE6AK, B07D3P7QXF, B000U5A7O...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, ...","[1225916962000, 1226250438000, 1226250601000, ...",67
4998,AGCQ6T75TJKMFFXC76VFEOKG7HKQ,"[B004G09BE6, B000BMZHX2, B0196KR6LA, B00DIFIP0...","[4.0, 5.0, 4.0, 5.0, 5.0, 5.0, 1.0, 5.0, 5.0, ...","[1373496507000, 1393273055000, 1396801073000, ...",67
4999,AHZ6FL6WVBPW4UUOLVETIRDGNPQA,"[B01N6ZOASM, B00QU5CR6E, B00JO6RO8C, B001EZYMF...","[1.0, 5.0, 5.0, 5.0, 5.0, 2.0, 4.0, 5.0, 5.0, ...","[1382724631000, 1387908775000, 1387909010000, ...",67

In [4]:
top_item_df = df.groupby("parent_asin").agg({
    "user_id": lambda x: x.tolist(),
    "rating": lambda x: x.tolist(),
    "timestamp": lambda x: x.tolist(),
}).reset_index(drop=False)
top_item_df["user_len"] = top_item_df["rating"].apply(lambda x: len(x))
top_item_df

,parent_asin,user_id,rating,timestamp,user_len
0,0062970704,"[AFUSWNVA72MMWHGYWJ652SYX2JJQ, AEX572KCHWTIW45...","[5.0, 3.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...","[1574625300520, 1621464729391, 1578846094359, ...",256
1,0071341196,"[AGFP4L46THLV4ZT2OKLNYP7FZ3LQ, AH263ZZPY6WT53H...","[5.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, ...","[1578173031817, 1292138499000, 1519408286370, ...",12
2,0140194614,"[AHCEZWPAA7PN47RVSNM22RVQJWCA, AHN3GXGA6X7QVQ5...","[5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, ...","[1331508697000, 1378503025000, 1490626534000, ...",13
3,0224073087,"[AG2RASOW27UAC37NQ53BAEXPC7IQ, AGC5XIO3A6IOMST...","[1.0, 4.0, 5.0, 3.0, 5.0]","[1433908964000, 1473204292000, 1441208274000, ...",5
4,0321528859,"[AFZFUIU3BWQ6UYQCUPZ5D6GVRS7A, AHMGBZBHCAYCUPW...","[5.0, 5.0, 4.0, 3.0, 2.0, 5.0, 4.0, 3.0]","[1239464798000, 1424117477000, 1471471481000, ...",8
...,...,...,...,...,...
368223,B0CJ66R5H2,"[AEHWGQSOFNOTX2QPHSIAFKC7CTNA, AERYN7BWF5Y5FRK...","[5.0, 1.0, 5.0, 4.0, 4.0]","[1683293649329, 1684290202466, 1683545442303, ...",5
368224,B0CJMJ22ZQ,"[AFHNITCJVVIK4RNIDDO3VWXLAPFA, AF77IMLF3ZL7MPI...","[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]","[1682827261129, 1683098173403, 1683554219914, ...",7
368225,B0CK2GYBK7,"[AGBXNANDMFG2B5Z35QPFDAZ6K7MQ, AH2CZB5YW5AWBED...","[5.0, 5.0, 5.0, 5.0, 5.0]","[1684615439308, 1685115928359, 1686111181551, ...",5
368226,B0CK88843T,"[AGMVGVFYNKE4EPHBBAUWBGZBIWZQ, AHNQKGSHAVU4AN4...","[4.0, 5.0, 5.0, 5.0, 5.0, 5.0]","[1686539061409, 1687221012551, 1685797400644, ...",6
368227,b014k9dj72,"[AHYMYFCLBNSFCPXW72DEMHJJFOIA, AHVSFC4Y4MIUO7N...","[3.0, 5.0, 5.0, 3.0, 5.0]","[1472787595000, 1486597568000, 1494465784000, ...",5

In [5]:
user_lens = top_item_df["user_len"].to_numpy()

top_item_df = top_item_df.iloc[np.argsort(user_lens)[::-1][:NUM_ITEM]].reset_index(drop=True)
top_item_df

,parent_asin,user_id,rating,timestamp,user_len
0,B075X8471B,"[AHGAOIZVODNHYMNCBV4DECZH42UQ, AEDHXXX2F66EMWO...","[5.0, 4.0, 5.0, 5.0, 2.0, 5.0, 5.0, 5.0, 5.0, ...","[1532476996921, 1482384682000, 1537322362789, ...",44948
1,B01K8B8YA8,"[AHGAOIZVODNHYMNCBV4DECZH42UQ, AFZUK3MTBIBEDQO...","[5.0, 5.0, 5.0, 5.0, 5.0, 3.0, 5.0, 5.0, 5.0, ...","[1513557475457, 1507749572526, 1538837322940, ...",39313
2,B07GZFM1ZM,"[AFZUK3MTBIBEDQOPAK3OATUOUKLA, AGJY4LG74YJEJBV...","[5.0, 5.0, 5.0, 1.0, 5.0, 5.0, 5.0, 1.0, 5.0, ...","[1586731581372, 1577755436567, 1545354325131, ...",36533
3,B010BWYDYA,"[AG57CQ6P4QWYMWUV6MTAOETUKHTA, AGA3PQKDGXZQB7D...","[5.0, 4.0, 2.0, 4.0, 5.0, 5.0, 4.0, 2.0, 5.0, ...","[1450507957000, 1469711844000, 1473698337000, ...",26228
4,B07S764D9V,"[AFA26DYXVLJYTYZ3KET77GE27N2A, AGUQFBJGLRCTSY4...","[5.0, 4.0, 4.0, 5.0, 4.0, 2.0, 2.0, 1.0, 5.0, ...","[1562372039826, 1456417953000, 1611676147082, ...",21534
...,...,...,...,...,...
29995,B08XYC4R9F,"[AEYJSBTHU3EUQVV27OKC54GKXF2A, AGR2MFSJHF6H45L...","[5.0, 5.0, 5.0, 5.0, 5.0, 2.0, 4.0, 1.0, 5.0, ...","[1645462018717, 1674359080547, 1647862939897, ...",86
29996,B0018SMVCS,"[AEQS7KCMJ5CP7UYGTDEXUAPRZPSQ, AGAINRYYKLF6S3T...","[4.0, 3.0, 5.0, 5.0, 5.0, 5.0, 4.0, 5.0, 4.0, ...","[1398343962000, 1418665055000, 1412448352000, ...",86
29997,B07F8YQXX2,"[AHEM37KVIW3Q4A2RV67HYOHURZ4Q, AFEI5DMO5TIDWZ6...","[5.0, 5.0, 3.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, ...","[1645104297169, 1619996664753, 1564663373974, ...",86
29998,B003S1NQ2C,"[AHGE7Q3EFNP2VEDJAMJ6GUCFAMYQ, AGDAJEDYRRK26JM...","[5.0, 5.0, 4.0, 5.0, 5.0, 4.0, 5.0, 5.0, 5.0, ...","[1415081553000, 1416790950000, 1419906367000, ...",86
29999,B0C5MTXVXV,"[AEBZPN243MTLKSG3M2MVG3ULZJFQ, AESYRPYUF3PZWZ4...","[2.0, 3.0, 2.0, 5.0, 5.0, 2.0, 1.0, 5.0, 5.0, ...","[1623136374872, 1663953402415, 1628439712385, ...",86

In [6]:
top_user_df = top_user_df.explode(["parent_asin", "rating", "timestamp"])

In [7]:
top_item_df = top_item_df.explode(["user_id", "rating", "timestamp"])

In [8]:
ddf = pd.merge(top_item_df, top_user_df, on=["user_id", "parent_asin"], how="inner")[["parent_asin", "user_id", "timestamp_x", "rating_x"]]
ddf = ddf.rename(columns={
    "rating_x": "rating", 
    "timestamp_x": "timestamp"
})
ddf

       parent_asin                       user_id      timestamp rating
0       B075X8471B  AHPOHKN4PU4W3V5PGFL7AGTAD2AA  1519588050500    4.0
1       B075X8471B  AEYTUWVOEPWUE7W2SUS3R7ELJNJQ  1482811902000    5.0
2       B075X8471B  AFQTRWQCJBYHBUIH5IYQC53LXQ5Q  1478395511000    4.0
3       B075X8471B  AHXO5KWH7Q2A2UTTLGQWIIR2ONPQ  1485029576000    3.0
4       B075X8471B  AE2ODZ4VYQ5FNNCONSHSNZM7PHSQ  1538170949468    5.0
...            ...                           ...            ...    ...
241670  B003S1NQ2C  AFUKJJRM5JPB4THXP5FLOJ4JCWIA  1476906788000    5.0
241671  B003S1NQ2C  AF6SAM7DQMQ2YFVXTPKFT5LWZXNQ  1447553273000    4.0
241672  B003S1NQ2C  AH4PWKRZFQ2YUEAZBFMEEI7M2DUA  1571512788347    5.0
241673  B003S1NQ2C  AGPCXVNN5W5LKQHFBDAWSTMXBEPA  1601574837421    5.0
241674  B0C5MTXVXV  AFCKQCTI6IZIYMS6WIGFJKMWBZEA  1671474199652    5.0

[241675 rows x 4 columns]

In [9]:
ddf = ddf.groupby("parent_asin").agg({
    "user_id": lambda x: x.tolist(),
    "rating": lambda x: x.tolist(),
    "timestamp": lambda x: x.tolist(),
}).reset_index(drop=False)

ddf["item_id"] = [i for i in range(len(ddf))]
ddf = ddf.explode(["user_id", "rating", "timestamp"])
ddf

      parent_asin                       user_id rating      timestamp  item_id
0      0062970704  AFUSWNVA72MMWHGYWJ652SYX2JJQ    5.0  1574625300520        0
0      0062970704  AFKKKGCSWQR5TKJPAFPLHF7VT26Q    5.0  1578518997397        0
0      0062970704  AF467J5VV3PDUURMEZOMXEHWFVMA    5.0  1577396717283        0
1      0345803507  AG36XH6HWU3XPKK2UK6E3Q5LOTJA    5.0  1424021579000        1
1      0345803507  AF2RJGZAZ2RDGEJ4PMILPBP2LKAQ    3.0  1417250008000        1
...           ...                           ...    ...            ...      ...
27582  B0CHR7WTKX  AG5JFFWME2HLKJBHBTIFXQVCCXFQ    5.0  1359381594000    27582
27582  B0CHR7WTKX  AHALYOX63S6CACZTHN7R24RVEX2A    5.0  1381060952000    27582
27582  B0CHR7WTKX  AFERKAUNTMTHHES5KZPJN3FL6BOQ    5.0  1357640292000    27582
27582  B0CHR7WTKX  AF4XEZZA3VLVSPD52G4F26C4X47A    5.0  1389553753000    27582
27582  B0CHR7WTKX  AHTYHQ2ZFOMSSOCPEBGD7TDCIWFA    5.0  1328406619000    27582

[241675 rows x 5 columns]

In [10]:
ddf = ddf.groupby("user_id").agg({
    "item_id": lambda x: x.tolist(),
    "parent_asin": lambda x: x.tolist(),
    "rating": lambda x: x.tolist(),
    "timestamp": lambda x: x.tolist(),
}).reset_index(drop=False)

ddf["user_id"] = [i for i in range(len(ddf))]
ddf = ddf.explode(["item_id", "parent_asin", "rating", "timestamp"])
ddf

      user_id item_id parent_asin rating      timestamp
0           0     548  B000CRFOMK    5.0  1422549495000
0           0    2528  B003MVZ60S    5.0  1340409020000
0           0    2671  B003XIJ566    5.0  1395513662000
0           0    2938  B004AM5RB6    1.0  1300396593000
0           0    3204  B004P15HD0    5.0  1374019952000
...       ...     ...         ...    ...            ...
4998     4998   25141  B0BDT4L4FJ    4.0  1499699601275
4998     4998   25267  B0BGJLM3T7    4.0  1658051722244
4998     4998   26025  B0BS2SLDVY    4.0  1596555554593
4998     4998   26494  B0BYJSHNQ6    4.0  1636381963196
4998     4998   27092  B0C5C9S5BF    4.0  1542761097586

[241675 rows x 5 columns]

In [11]:
len(ddf["item_id"].unique()), len(ddf["user_id"].unique())

(27583, 4999)

In [12]:
ddf.to_pickle("../../data/interim/rating.pkl")